GET http://localhost:7000/artists

###
POST http://localhost:7000/artists
Content-Type: application/json

{
  "name": "Carl"
}

###
DELETE http://localhost:7000/artists/5a17701ab09b1d10e2d1005c

###
PATCH http://localhost:7000/artists/5a176583b262480c4c79078d
Content-Type: application/json

{
  "name": ""
}